require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'Tirak' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # Fix fmt consteval compilation errors with Xcode 26.4+
    fmt_base = File.join(installer.sandbox.pod_dir('fmt'), 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      patched = content.gsub(/^#\\s*define FMT_USE_CONSTEVAL 1$/, '# define FMT_USE_CONSTEVAL 0')
      if patched != content
        File.chmod(0644, fmt_base)
        File.write(fmt_base, patched)
      end
    end
    fmt_format_inl = File.join(installer.sandbox.pod_dir('fmt'), 'include', 'fmt', 'format-inl.h')
    if File.exist?(fmt_format_inl)
      content = File.read(fmt_format_inl)
      patched = content.gsub(/^#\\s*define FMT_USE_CONSTEVAL 1$/, '# define FMT_USE_CONSTEVAL 0')
      if patched != content
        File.chmod(0644, fmt_format_inl)
        File.write(fmt_format_inl, patched)
      end
    end
    fmt_format_h = File.join(installer.sandbox.pod_dir('fmt'), 'include', 'fmt', 'format.h')
    if File.exist?(fmt_format_h)
      content = File.read(fmt_format_h)
      patched = content.gsub(/^#\\s*define FMT_USE_CONSTEVAL 1$/, '# define FMT_USE_CONSTEVAL 0')
      if patched != content
        File.chmod(0644, fmt_format_h)
        File.write(fmt_format_h, patched)
      end
    end

    # Fix React Native build scripts when the project path contains spaces.
    with_environment = File.join(config[:reactNativePath], 'scripts', 'xcode', 'with-environment.sh')
    if File.exist?(with_environment)
      content = File.read(with_environment)
      patched = content.gsub("  $1\n", "  \"$@\"\n")
      if patched != content
        File.chmod(0755, with_environment)
        File.write(with_environment, patched)
      end
      File.chmod(0755, with_environment)
    end

    installer.pods_project.targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        next unless phase.shell_script

        phase.shell_script = phase.shell_script.gsub(
          '/bin/sh -c "$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT"',
          '"$WITH_ENVIRONMENT" "$SCRIPT_PHASES_SCRIPT"'
        )

        phase.shell_script = phase.shell_script.gsub(
          'bash -l -c "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"',
          'bash -l "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"'
        )
      end
    end

    expo_constants_script = File.expand_path(
      '../node_modules/expo-constants/scripts/get-app-config-ios.sh',
      Pod::Config.instance.installation_root.to_s
    )
    if File.exist?(expo_constants_script)
      content = File.read(expo_constants_script)
      patched = content.gsub('PROJECT_DIR_BASENAME=$(basename $PROJECT_DIR)', 'PROJECT_DIR_BASENAME=$(basename "$PROJECT_DIR")')
      if patched != content
        File.chmod(0755, expo_constants_script)
        File.write(expo_constants_script, patched)
      end
      File.chmod(0755, expo_constants_script)
    end

    expo_constants_podspec = File.expand_path(
      '../node_modules/expo-constants/ios/EXConstants.podspec',
      Pod::Config.instance.installation_root.to_s
    )
    if File.exist?(expo_constants_podspec)
      content = File.read(expo_constants_podspec)
      patched = content.gsub(
        'bash -l -c "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"',
        'bash -l "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"'
      )
      if patched != content
        File.chmod(0644, expo_constants_podspec)
        File.write(expo_constants_podspec, patched)
      end
    end

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
