import React from 'react';
import { fireEvent, render } from '@testing-library/react-native';
const mockArchive = jest.fn();
let mockMutationIndex = 0;
const mockExperience = {id:'service-1',title:'Canal walk',description:'A local cultural walk',price:1800,currency:'THB',durationMinutes:180,keywords:[],isActive:true};
jest.mock('expo-router', () => ({ useRouter: () => ({ back:jest.fn(), replace:jest.fn() }) }));
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: require('react-native').View }));
jest.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string) => key }) }));
jest.mock('@/stores/auth-store', () => ({ useAuthStore: (select: any) => select({ user: {id:'owner'} }) }));
jest.mock('@/stores/toast-store', () => ({ useToast: () => ({success:jest.fn(),error:jest.fn()}) }));
jest.mock('@/services/api/companion/experience', () => ({ useExperiences: () => ({data:{data:{items:[mockExperience]}}, isLoading:false, refetch:jest.fn()}), useCreateExperience: () => ({isPending:false}), archiveExperience: jest.fn(), updateExperience: jest.fn(), invalidateExperienceQueries: jest.fn(), readExperienceDrafts: jest.fn() }));
jest.mock('@tanstack/react-query', () => ({ useQueryClient: () => ({}), useQuery: () => ({data:[]}), useMutation: () => { mockMutationIndex++; return {mutate:mockArchive,isPending:false,isError:false,reset:jest.fn()}; } }));
const ServicesScreen = require('@/app/(supplier)/services/index').default;
test('archive requires a separate confirmation and cancellation leaves the service unchanged', () => {
  const ui=render(<ServicesScreen />);
  fireEvent.press(ui.getByText('editServices.removeFromProfile'));
  expect(mockArchive).not.toHaveBeenCalled();
  expect(ui.getByText('editServices.archiveExplanation')).toBeTruthy();
  fireEvent.press(ui.getByText('common.cancel'));
  expect(mockArchive).not.toHaveBeenCalled();
  fireEvent.press(ui.getByText('editServices.removeFromProfile'));
  fireEvent.press(ui.getByText('editServices.confirmRemove'));
  expect(mockArchive).toHaveBeenCalledWith('service-1');
});
